---
- name: ensure endeca pid gets created in correct place
  lineinfile: 
  args:
    create: yes
    mode: 0755
    dest: "{{ install_root }}/endeca/PlatformServices/11.1.0/tools/server/bin/setenv.sh"
    regexp: "CATALINA_PID=.*"
    line: "CATALINA_PID={{ pid_dir }}/{{ endeca_platformservices_service }}.pid"

- name: create platformservices init script
  template:
  args:
    src: "platformservices_init.j2"
    dest: "/etc/init.d/{{ endeca_platformservices_service }}"
    mode: 0755
  sudo: yes
  sudo_user: root

- name: start service
  service:
  args:
    name: "{{ endeca_platformservices_service }}"
    enabled: yes
    state: started
  sudo: yes
  sudo_user: root

