---
#
# This role should be run with sudo=yes sudo_user={{ install_user }}.
#

#
# Platform Services
#

- set_fact:
    install_archive: "V45999-01.zip"
    install_executable: "OCplatformservices11.1.0-Linux64.bin"

- name: temporary directory for install
  register: mktemp
  command: mktemp -d

- name: download installation archive
  get_url:
  args:
    url: "{{ install_archive_url }}"
    dest: "{{ playbook_dir }}/{{ install_archive }}"
  when: install_archive_url is defined

- name: expand platformservices archive
  unarchive: 
    src="{{ install_archive }}"
    dest="{{ mktemp.stdout }}"
    creates="{{ mktemp.stdout }}/{{ install_executable }}"

- name: ensure platformservices install file is executable
  file:
  args:
    path: "{{ mktemp.stdout }}/{{ install_executable }}"
    mode: 0744

- name: create silent install file for platformservices
  template: 
  args:
    src: "platformservices_silent.j2"
    dest: "{{ mktemp.stdout }}/platformservices_silent.txt"

- name: install platform services
  command: "{{ mktemp.stdout }}/{{ install_executable }} --silent --target {{ install_root }} < '{{ mktemp.stdout }}/platformservices_silent.txt' 2>&1 > /tmp/platformservices_install.log"
  args:
    creates: "{{ install_root }}/endeca/PlatformServices"

- include: init.yml tags=configure_service
    
- name: clean up temporary directory
  file: 
    state=absent 
    path="{{ mktemp.stdout }}"

#- name: source platformservices environment vars
#  lineinfile:
#  args:
#    dest: "/home/{{ endeca_user }}/.bashrc"
#    line: "source {{ endeca_root }}/endeca/PlatformServices/workspace/setup/installer_sh.ini"

